<?php

/*
 * SPDX-FileCopyrightText: 2026 Humdek, University of Bern
 * SPDX-License-Identifier: MPL-2.0
 */

declare(strict_types=1);

use App\Util\FreshTestInstallSchedulerGuard;

$projectDir = realpath(__DIR__ . '/..');
if ($projectDir === false) {
    fwrite(STDERR, "Cannot resolve project root from " . __DIR__ . "\n");
    exit(2);
}

require_once $projectDir . '/vendor/autoload.php';

$adminEmail = getenv('SELFHELP_TEST_ADMIN_EMAIL') ?: 'admin@unibe.ch';
$adminName = getenv('SELFHELP_TEST_ADMIN_NAME') ?: 'Admin';
$adminPassword = getenv('SELFHELP_TEST_ADMIN_PASSWORD') ?: 'admin';

$exitCode = 0;
$schedulerGuard = new FreshTestInstallSchedulerGuard();
$schedulerWasPaused = false;

try {
    $schedulerWasPaused = $schedulerGuard->pauseIfRunning($projectDir);
    if ($schedulerWasPaused) {
        echo "Paused local Docker scheduler to avoid cache lock races.\n";
    }

    echo "Cleaning generated plugin state before Symfony boots...\n";
    removePath($projectDir . '/config/selfhelp_plugin_bundles.php');
    removePath($projectDir . '/config/selfhelp_plugin_bundles.php.tmp');
    removePath($projectDir . '/selfhelp.plugins.lock.json');
    removePath($projectDir . '/selfhelp.plugins.lock.json.tmp');
    removePath($projectDir . '/selfhelp.plugins.lock.json.bak');
    removePath($projectDir . '/var/plugin_safe_mode.lock');
    removePath($projectDir . '/var/plugin-composer');
    removePath($projectDir . '/var/plugins');
    removePath($projectDir . '/public/plugin-artifacts');
    removePath($projectDir . '/var/cache');

    $php = PHP_BINARY;

    run([$php, 'bin/console', 'doctrine:database:drop', '--force', '--if-exists'], $projectDir);
    run([$php, 'bin/console', 'doctrine:database:create'], $projectDir);
    run([$php, 'bin/console', 'doctrine:migrations:migrate', '--no-interaction'], $projectDir);
    run([$php, 'bin/console', 'app:create-admin-user', $adminEmail, $adminName, '--password=' . $adminPassword], $projectDir);
    // Fresh installs get the polished hero landing on `home` instead of the placeholder.
    run([$php, 'bin/console', 'app:examples:seed-hero-home'], $projectDir, allowFailure: true);
    run([$php, 'bin/console', 'cache:pool:clear', '--all'], $projectDir, allowFailure: true);
    run([$php, 'bin/console', 'cache:clear'], $projectDir);

    echo "\nFresh test install ready. Admin user: {$adminEmail}\n";
} catch (Throwable $exception) {
    fwrite(STDERR, $exception->getMessage() . "\n");
    $exitCode = is_int($exception->getCode()) && $exception->getCode() > 0 ? $exception->getCode() : 1;
} finally {
    try {
        $schedulerGuard->resumeIfPaused($projectDir, $schedulerWasPaused);
        if ($schedulerWasPaused) {
            echo "Restarted local Docker scheduler.\n";
        }
    } catch (Throwable $exception) {
        fwrite(STDERR, $exception->getMessage() . "\n");
        $exitCode = 1;
    }
}

exit($exitCode);

/**
 * @param list<string> $command
 */
function run(array $command, string $cwd, bool $allowFailure = false): void
{
    echo "\n> " . implode(' ', array_map('quoteForDisplay', $command)) . "\n";

    $process = proc_open(
        $command,
        [
            0 => STDIN,
            1 => STDOUT,
            2 => STDERR,
        ],
        $pipes,
        $cwd
    );

    if (!is_resource($process)) {
        throw new RuntimeException('Failed to start command.');
    }

    $exitCode = proc_close($process);
    if ($exitCode !== 0) {
        if ($allowFailure) {
            fwrite(STDERR, "Command failed with exit code {$exitCode}; continuing.\n");
            return;
        }
        throw new RuntimeException("Command failed with exit code {$exitCode}.", $exitCode);
    }
}

function removePath(string $path): void
{
    if (!file_exists($path) && !is_link($path)) {
        return;
    }

    if (is_file($path) || is_link($path)) {
        if (!@unlink($path) && file_exists($path)) {
            throw new RuntimeException("Failed to remove file: {$path}");
        }
        echo "Removed {$path}\n";
        return;
    }

    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );

    foreach ($iterator as $item) {
        $itemPath = $item->getPathname();
        // Skip .git directories and their contents to avoid Windows file lock issues
        if (str_contains($itemPath, DIRECTORY_SEPARATOR . '.git' . DIRECTORY_SEPARATOR) || str_ends_with($itemPath, DIRECTORY_SEPARATOR . '.git')) {
            continue;
        }
        if ($item->isDir() && !$item->isLink()) {
            if (!@rmdir($itemPath) && is_dir($itemPath)) {
                // Directory may contain .git subdirectory - that's acceptable
                echo "Skipped removing directory {$itemPath} (will be regenerated by composer)\n";
            }
        } elseif (!@unlink($itemPath) && file_exists($itemPath)) {
            throw new RuntimeException("Failed to remove file: {$itemPath}");
        }
    }

    // Final directory removal may fail on Windows due to .git file locks - that's acceptable
    // since composer will regenerate the plugin-composer directory anyway
    if (!@rmdir($path) && is_dir($path)) {
        echo "Skipped removing {$path} (will be regenerated by composer)\n";
        return;
    }

    echo "Removed {$path}\n";
}

function quoteForDisplay(string $value): string
{
    if (preg_match('~^[A-Za-z0-9_@%+=:,./\\\\-]+$~', $value) === 1) {
        return $value;
    }

    return "'" . str_replace("'", "'\\''", $value) . "'";
}
