<?php

/*
 * SPDX-FileCopyrightText: 2026 Humdek, University of Bern
 * SPDX-License-Identifier: MPL-2.0
 */


declare(strict_types=1);

namespace App\Plugin\Bundle;

use App\Repository\Plugin\PluginRepository;

/**
 * Writes `config/selfhelp_plugin_bundles.php` atomically.
 *
 * `config/bundles.php` requires this file at boot when plugins are
 * enabled; the file is regenerated by the install/update/uninstall
 * orchestrators (and the doctor command for self-repair). The writer
 * never edits files outside `config/`.
 *
 * The generated file is intentionally minimal so the host can boot
 * even when the plugin layer is degraded — it is just an array of
 * `BundleClass::class => ['all' => true]`. Plugins that ship without
 * a backend bundle (e.g. frontend-only plugins) are omitted.
 *
 * Atomicity: the writer writes to a temporary file in the same
 * directory and renames into place. On Windows the temporary file is
 * removed first to avoid `rename()` failures.
 */
final class PluginBundlesFileWriter
{
    public function __construct(
        private readonly PluginRepository $plugins,
        private readonly string $projectDir,
    ) {
    }

    public function regenerate(): string
    {
        $path = $this->configPath();
        $lines = $this->buildLines();
        $contents = $this->renderFile($lines);

        $tmp = $path . '.tmp';
        if (file_put_contents($tmp, $contents, LOCK_EX) === false) {
            throw new \RuntimeException('Failed to write temporary plugin bundles file: ' . $tmp);
        }

        if (is_file($path) && PHP_OS_FAMILY === 'Windows') {
            @unlink($path);
        }
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            throw new \RuntimeException(sprintf('Failed to rename %s to %s.', $tmp, $path));
        }
        $this->invalidateConfigCacheResources($path);

        return $path;
    }

    /**
     * @return list<string>
     */
    private function buildLines(): array
    {
        $lines = [];
        foreach ($this->plugins->findEnabled() as $plugin) {
            $class = $plugin->getBackendBundleClass();
            if ($class === null || $class === '') {
                continue;
            }
            $lines[] = sprintf('    %s::class => [\'all\' => true],', $class);
        }
        return $lines;
    }

    /**
     * @param list<string> $bundleLines
     */
    private function renderFile(array $bundleLines): string
    {
        $now = (new \DateTimeImmutable('now', new \DateTimeZone('UTC')))->format(DATE_ATOM);
        $bundleBlock = $bundleLines === [] ? "    // no plugin bundles enabled" : implode("\n", $bundleLines);

        return <<<PHP
<?php

/*
 * SPDX-FileCopyrightText: 2026 Humdek, University of Bern
 * SPDX-License-Identifier: MPL-2.0
 */


/**
 * Generated by App\\Plugin\\Bundle\\PluginBundlesFileWriter at {$now}.
 *
 * DO NOT EDIT BY HAND. This file is rewritten atomically by the plugin
 * installer / updater / uninstaller and by the doctor command. Any
 * manual changes will be lost on the next operation.
 *
 * `config/bundles.php` includes this file when SELFHELP_DISABLE_PLUGINS
 * is not set. See docs/plugins/installation.md for details.
 */

return [
{$bundleBlock}
];

PHP;
    }

    public function configPath(): string
    {
        return $this->projectDir . '/config/selfhelp_plugin_bundles.php';
    }

    private function invalidateConfigCacheResources(string $generatedPath): void
    {
        $bundlesPath = $this->projectDir . '/config/bundles.php';
        if (is_file($bundlesPath)) {
            @touch($bundlesPath);
        }
        if (function_exists('opcache_invalidate')) {
            @opcache_invalidate($generatedPath, true);
            if (is_file($bundlesPath)) {
                @opcache_invalidate($bundlesPath, true);
            }
        }
    }
}
